//! kat_synth_entropy — analytic entropy from Markov matrix must match independent empirical estimator.
//!
//! DEFENDS AGAINST: "green but broken" test that compares a number to itself.
//!
//! This test proves the fixture's own target (entropy_bits_per_byte computed analytically
//! from the Markov transition matrix P) is correct by verifying it against a SECOND,
//! INDEPENDENT estimator: empirical plug-in entropy rate computed from the sample bytes.
//!
//! The Markov source is GENUINE:
//! - P is defined BEFORE generation (not extracted from it)
//! - Bytes are SAMPLED from P (not uniform random)
//! - H_analytic comes from P's stationary distribution + conditional entropies
//! - H_empirical comes from sample counts (independent computation)
//!
//! PASS ⟺ |H_analytic − H_empirical| ≤ 0.02 bits/byte
//!     AND H_analytic ≤ H0 − 0.5 (genuinely structured, not degenerate)

use qilm_data::synth;
use rand::rngs::StdRng;
use rand::{SeedableRng, Rng};
use std::collections::HashMap;

#[test]
fn kat_synth_entropy() {
    // Generate 2.5M bytes from a known order-1 Markov source (K=16, 256 transitions).
    const N_BYTES: usize = 2_500_000;
    const ORDER: usize = 1;
    const SEED: u64 = 42;
    const TOLERANCE_BITS_PER_BYTE: f64 = 0.02;

    eprintln!("Generating {} bytes with order={}, seed={}", N_BYTES, ORDER, SEED);
    let (bytes, truth) = synth::synth_markov(ORDER, SEED, N_BYTES);

    // H_analytic: computed from the transition matrix before generation.
    let h_analytic = truth.entropy_bits_per_byte;
    let h0 = truth.order0_entropy;

    eprintln!("H_analytic = {:.6} bits/byte (from matrix)", h_analytic);
    eprintln!("H0         = {:.6} bits/byte (marginal)", h0);

    // ===== H_empirical: independent plug-in estimator from sample =====
    // Build empirical transition matrix from the generated bytes.
    let mut transition_counts: HashMap<Vec<u8>, HashMap<u8, u64>> = HashMap::new();

    for i in ORDER..N_BYTES {
        let context = bytes[i - ORDER..i].to_vec();
        let byte = bytes[i];
        *transition_counts
            .entry(context)
            .or_insert_with(HashMap::new)
            .entry(byte)
            .or_insert(0) += 1;
    }

    // Empirical entropy rate: H_emp = Σ_context P(context) · H(X | context).
    let mut h_empirical = 0.0;
    let n_transitions = (N_BYTES - ORDER) as f64;

    for (_context, next_bytes) in &transition_counts {
        let context_count: u64 = next_bytes.values().sum();
        if context_count == 0 {
            continue;
        }

        let p_context = context_count as f64 / n_transitions;
        let mut h_given_context = 0.0;

        for (&_byte, &count) in next_bytes {
            if count > 0 {
                let p_byte_given_context = count as f64 / context_count as f64;
                h_given_context -= p_byte_given_context * p_byte_given_context.log2();
            }
        }

        h_empirical += p_context * h_given_context;
    }

    eprintln!("H_empirical = {:.6} bits/byte (from sample)", h_empirical);

    let diff = (h_analytic - h_empirical).abs();
    eprintln!("|H_analytic - H_empirical| = {:.6} bits/byte", diff);

    // ===== Assertions =====

    // Primary: entropy rate matches within tolerance.
    assert!(
        diff <= TOLERANCE_BITS_PER_BYTE,
        "Entropy rate mismatch: H_analytic={:.6}, H_empirical={:.6}, diff={:.6}, threshold={:.6}",
        h_analytic, h_empirical, diff, TOLERANCE_BITS_PER_BYTE
    );

    // Secondary: source is genuinely structured (not degenerate uniform).
    let margin = h0 - h_analytic;
    eprintln!("Margin H0 - H = {:.6} bits/byte (should be > 0.5)", margin);
    assert!(
        h_analytic <= h0 - 0.5,
        "Source not structured: H_analytic={:.6}, H0={:.6}, margin={:.6} (need > 0.5)",
        h_analytic, h0, margin
    );
}

#[test]
fn test_synth_determinism() {
    // Same seed must produce byte-identical output and identical entropy values.
    // Use 1_000_000 bytes to satisfy state space requirement: K^(order+1)=256 <= 1_000_000/2000=500
    const N_BYTES: usize = 1_000_000;
    const ORDER: usize = 1;
    const SEED: u64 = 7;

    let (bytes1, truth1) = synth::synth_markov(ORDER, SEED, N_BYTES);
    let (bytes2, truth2) = synth::synth_markov(ORDER, SEED, N_BYTES);

    // Bytes must be identical.
    assert_eq!(
        bytes1, bytes2,
        "Same seed should produce byte-identical output"
    );

    // Truth values should be identical (within floating-point precision).
    let ent_diff = (truth1.entropy_bits_per_byte - truth2.entropy_bits_per_byte).abs();
    let order0_diff = (truth1.order0_entropy - truth2.order0_entropy).abs();

    assert!(
        ent_diff < 1e-10,
        "Entropy must be identical for same seed, diff={}",
        ent_diff
    );
    assert!(
        order0_diff < 1e-10,
        "Order-0 entropy must be identical for same seed, diff={}",
        order0_diff
    );
}

/// Anti-vacuity canary: proves the test can FAIL on a wrong source.
///
/// This test feeds the empirical estimator a uniform-random byte stream of the same length.
/// It asserts that the empirical entropy of this degenerate source differs from H_analytic
/// by MORE than 0.5 bits/byte, proving the test can discriminate between real and fake sources.
///
/// If this test FAILS, it means the entropy computation itself is broken.
#[test]
fn test_entropy_test_can_say_no() {
    const N_BYTES: usize = 2_500_000;
    const ORDER: usize = 1;
    const SEED_MARKOV: u64 = 42;
    const SEED_UNIFORM: u64 = 123;

    // Get the analytic entropy from the real Markov source.
    let (_bytes_markov, truth) = synth::synth_markov(ORDER, SEED_MARKOV, N_BYTES);
    let h_analytic = truth.entropy_bits_per_byte;

    eprintln!(
        "Canary: H_analytic from Markov source = {:.6}",
        h_analytic
    );

    // Generate a uniform-random byte stream (degenerate source, no structure).
    let mut seed_array = [0u8; 32];
    seed_array[0..8].copy_from_slice(&SEED_UNIFORM.to_le_bytes());
    let mut rng = StdRng::from_seed(seed_array);

    let bytes_uniform: Vec<u8> = (0..N_BYTES).map(|_| rng.gen()).collect();

    // Compute empirical entropy rate on the uniform stream.
    let mut transition_counts: HashMap<Vec<u8>, HashMap<u8, u64>> = HashMap::new();

    for i in ORDER..N_BYTES {
        let context = bytes_uniform[i - ORDER..i].to_vec();
        let byte = bytes_uniform[i];
        *transition_counts
            .entry(context)
            .or_insert_with(HashMap::new)
            .entry(byte)
            .or_insert(0) += 1;
    }

    let mut h_uniform_empirical = 0.0;
    let n_transitions = (N_BYTES - ORDER) as f64;

    for (_context, next_bytes) in &transition_counts {
        let context_count: u64 = next_bytes.values().sum();
        if context_count == 0 {
            continue;
        }

        let p_context = context_count as f64 / n_transitions;
        let mut h_given_context = 0.0;

        for (&_byte, &count) in next_bytes {
            if count > 0 {
                let p_byte_given_context = count as f64 / context_count as f64;
                h_given_context -= p_byte_given_context * p_byte_given_context.log2();
            }
        }

        h_uniform_empirical += p_context * h_given_context;
    }

    eprintln!("Canary: H_empirical on uniform = {:.6}", h_uniform_empirical);

    let discriminability = (h_uniform_empirical - h_analytic).abs();
    eprintln!(
        "Canary: |H_uniform - H_markov| = {:.6} (should be > 0.5)",
        discriminability
    );

    // The uniform source should have much higher entropy than the structured Markov source.
    // If the difference is small, the test cannot discriminate, proving it's broken.
    assert!(
        discriminability > 0.5,
        "Test cannot discriminate: uniform entropy {:.6} too close to Markov entropy {:.6}, diff={}. \
         This proves kat_synth_entropy is vacuous and cannot detect a wrong source.",
        h_uniform_empirical, h_analytic, discriminability
    );
}
