//! Phase report generator tests with anti-vacuity canaries (AGENTS.md Rule 2).
//!
//! test_phase_report_proceed: fixture where all gates pass -> report says PROCEED
//! test_phase_report_can_say_stop: fixture where project_kill gate FAILS -> report says STOP
//!
//! The second test proves the verdict logic can output STOP, not just rubber-stamp PROCEED.

use qilm_train::gate::GateOutcome;
use qilm_train::provenance::{write_metrics, MetricsInput};
use qilm_train::report::{compute_verdict, generate_phase_report, ReportConfig, Verdict};
use serde_json::json;
use std::path::Path;

fn workspace_root() -> std::path::PathBuf {
    Path::new(env!("CARGO_MANIFEST_DIR"))
        .parent()
        .unwrap()
        .to_path_buf()
}

/// Test that a phase report correctly says PROCEED when all gates pass.
/// This is the "good path" test: metrics are valid, verdict is PROCEED.
#[test]
fn test_phase_report_proceed() {
    let runs_dir = tempfile::tempdir().unwrap();
    let results_dir = tempfile::tempdir().unwrap();
    // Redirect the report OUTPUT to a tempdir so this test never writes into —
    // and then deletes — the committed reports/PHASE-0.md in the working tree.
    // workspace_root stays the real repo because provenance validation
    // (git_sha + code_fingerprint) is anchored there.
    let reports_dir = tempfile::tempdir().unwrap();

    // Write a run with Phase 0 metrics (gradcheck only).
    let input = MetricsInput {
        config_sha256: "phase0-proceed-config".to_string(),
        dataset_sha256: "none".to_string(),
        seed: 0,
        backend: "cpu-oracle".to_string(),
        wall_clock_s: 0.5,
        metrics: json!({
            "gradcheck_max_rel_err": 5e-6  // Below threshold of 1e-4
        }),
    };
    write_metrics(runs_dir.path(), "phase0-pass", input).unwrap();

    let cfg = ReportConfig {
        runs_dir: runs_dir.path(),
        gates_toml: &workspace_root().join("gates.toml"),
        results_dir: results_dir.path(),
        reports_dir: reports_dir.path(),
        workspace_root: &workspace_root(),
    };

    // Generate Phase 0 report
    let result = generate_phase_report(&cfg, 0);
    assert!(
        result.is_ok(),
        "Phase 0 report generation must succeed with valid run"
    );

    // Verify PHASE-0.md was written to the (temp) reports dir
    let phase0_path = reports_dir.path().join("PHASE-0.md");
    assert!(
        phase0_path.exists(),
        "PHASE-0.md must be written to reports_dir after generate_phase_report(0)"
    );

    // Verify it contains PROCEED
    let content = std::fs::read_to_string(&phase0_path).unwrap();
    assert!(
        content.contains("PROCEED"),
        "Phase 0 report must contain PROCEED (all gates pass)"
    );
    assert!(
        content.starts_with("<!-- GENERATED by"),
        "Phase report must be generator-stamped"
    );
    // No cleanup of the working tree needed: the tempdir is removed on drop.
}

/// Test that the verdict logic can say STOP when a project_kill gate fails.
/// This is the anti-vacuity canary: proves the code path to STOP actually works.
#[test]
fn test_phase_report_can_say_stop() {
    // Create a fixture where a project_kill gate FAILS.
    // Phase 0 has no project_kill gates, so we'll construct the gate list manually
    // and test compute_verdict directly.

    let gates = vec![(
        "collapse".to_string(),
        GateOutcome::Fail {
            measured: 0.2, // Below threshold of 0.50
            threshold: 0.50,
        },
        "Non-collapse test".to_string(),
        "project_kill".to_string(),
    )];

    let verdict = compute_verdict(&gates);

    // The verdict must be STOP, not PROCEED
    match verdict {
        Verdict::Stop {
            gate,
            measured,
            threshold,
        } => {
            assert_eq!(gate, "collapse");
            assert_eq!(measured, 0.2);
            assert_eq!(threshold, 0.50);
            // Success: the canary fires. The verdict logic CAN say STOP.
        }
        Verdict::Proceed => {
            panic!("Verdict should be STOP, not PROCEED, when a project_kill gate fails");
        }
        Verdict::ProceedNarrowed { .. } => {
            panic!("Verdict should be STOP, not PROCEED_NARROWED, when a project_kill gate fails");
        }
    }
}

/// Test that narrow gate failures produce PROCEED_NARROWED, not PROCEED.
#[test]
fn test_phase_report_can_say_narrowed() {
    // Create a fixture where a narrow gate FAILS but no project_kill gate fails.
    let gates = vec![(
        "invariance".to_string(),
        GateOutcome::Fail {
            measured: 0.40,
            threshold: 0.50,
        },
        "Invariance margin test".to_string(),
        "narrow".to_string(),
    )];

    let verdict = compute_verdict(&gates);

    match verdict {
        Verdict::ProceedNarrowed {
            gate,
            measured,
            threshold,
        } => {
            assert_eq!(gate, "invariance");
            assert_eq!(measured, 0.40);
            assert_eq!(threshold, 0.50);
            // Success: narrow failure produces narrowed verdict.
        }
        Verdict::Stop { .. } => {
            panic!("Verdict should be PROCEED_NARROWED, not STOP, when only a narrow gate fails");
        }
        Verdict::Proceed => {
            panic!("Verdict should be PROCEED_NARROWED, not PROCEED, when a narrow gate fails");
        }
    }
}

/// Test that infra gate failures don't affect the verdict.
/// Infra gates are informational only.
#[test]
fn test_phase_report_infra_gates_dont_affect_verdict() {
    // Create a fixture where only infra gates are present/fail.
    let gates = vec![(
        "gradcheck".to_string(),
        GateOutcome::Pass {
            measured: 5e-6,
            threshold: 1e-4,
        },
        "Gradcheck test".to_string(),
        "infra".to_string(),
    )];

    let verdict = compute_verdict(&gates);

    // Should be PROCEED since no project_kill or narrow gates failed
    assert_eq!(verdict, Verdict::Proceed);
}

/// Test that project_kill gates take precedence over narrow gates.
#[test]
fn test_phase_report_project_kill_precedence() {
    let gates = vec![
        (
            "collapse".to_string(),
            GateOutcome::Fail {
                measured: 0.2,
                threshold: 0.50,
            },
            "Collapse test".to_string(),
            "project_kill".to_string(),
        ),
        (
            "invariance".to_string(),
            GateOutcome::Fail {
                measured: 0.40,
                threshold: 0.50,
            },
            "Invariance test".to_string(),
            "narrow".to_string(),
        ),
    ];

    let verdict = compute_verdict(&gates);

    // Should be STOP (project_kill takes precedence)
    match verdict {
        Verdict::Stop { gate, .. } => {
            assert_eq!(gate, "collapse");
        }
        _ => {
            panic!("Verdict should be STOP when project_kill gate fails, even if narrow gates also fail");
        }
    }
}
