//! T0.9 — the anti-fake report generator (VERIFICATION.md §4.2).
//!
//! test_report_refuses_fabrication: a metrics.json whose git_sha != HEAD must
//! make `report` return non-zero (Err) and write nothing.
//! test_report_roundtrip: a valid run's numbers must appear in the generated
//! RESULTS.md/.json unchanged (no transcription).

use qilm_train::provenance::{write_metrics, MetricsInput};
use qilm_train::report::{generate, ReportConfig};
use serde_json::json;
use std::path::Path;

fn workspace_root() -> std::path::PathBuf {
    Path::new(env!("CARGO_MANIFEST_DIR"))
        .parent()
        .unwrap()
        .to_path_buf()
}

#[test]
fn test_report_refuses_fabrication() {
    let runs_dir = tempfile::tempdir().unwrap();
    let results_dir = tempfile::tempdir().unwrap();

    // Write a run with a WRONG git_sha directly (bypassing write_metrics,
    // which always stamps the real HEAD -- this simulates a fabricated or
    // stale run artifact).
    let bad_run_dir = runs_dir.path().join("bad-run");
    std::fs::create_dir_all(&bad_run_dir).unwrap();
    let bad_record = json!({
        "git_sha": "0000000000000000000000000000000000dead",
        "config_sha256": "abc",
        "dataset_sha256": "none",
        "code_fingerprint": "def",
        "seed": 0,
        "backend": "cpu",
        "wall_clock_s": 1.0,
        "host": "test-host",
        "metrics": { "gradcheck_max_rel_err": 0.00001 }
    });
    std::fs::write(
        bad_run_dir.join("metrics.json"),
        serde_json::to_string_pretty(&bad_record).unwrap(),
    )
    .unwrap();

    let cfg = ReportConfig {
        runs_dir: runs_dir.path(),
        gates_toml: &workspace_root().join("gates.toml"),
        results_dir: results_dir.path(),
        workspace_root: &workspace_root(),
    };

    let result = generate(&cfg);
    assert!(
        result.is_err(),
        "report must refuse a run whose git_sha != HEAD"
    );

    // Nothing written.
    assert!(!results_dir.path().join("RESULTS.md").exists());
    assert!(!results_dir.path().join("RESULTS.json").exists());
}

#[test]
fn test_report_roundtrip() {
    let runs_dir = tempfile::tempdir().unwrap();
    let results_dir = tempfile::tempdir().unwrap();

    let measured_value = 0.0000123456_f64;
    let input = MetricsInput {
        config_sha256: "roundtrip-config".to_string(),
        dataset_sha256: "none".to_string(),
        seed: 0,
        backend: "cpu-scalar-oracle".to_string(),
        wall_clock_s: 0.01,
        metrics: json!({ "gradcheck_max_rel_err": measured_value }),
    };
    write_metrics(runs_dir.path(), "roundtrip-run", input).unwrap();

    let cfg = ReportConfig {
        runs_dir: runs_dir.path(),
        gates_toml: &workspace_root().join("gates.toml"),
        results_dir: results_dir.path(),
        workspace_root: &workspace_root(),
    };

    generate(&cfg).expect("a valid, HEAD-matching run must generate successfully");

    let md_path = results_dir.path().join("RESULTS.md");
    let json_path = results_dir.path().join("RESULTS.json");
    assert!(md_path.exists());
    assert!(json_path.exists());

    let md = std::fs::read_to_string(&md_path).unwrap();
    assert!(
        md.starts_with("<!-- GENERATED by"),
        "RESULTS.md must be generator-stamped"
    );

    let json_contents = std::fs::read_to_string(&json_path).unwrap();
    let parsed: serde_json::Value = serde_json::from_str(&json_contents).unwrap();

    // The exact measured number must appear, unmodified, in the generated
    // JSON -- pulled from metrics.json, not retyped.
    let found = parsed["runs"][0]["metrics"]["gradcheck_max_rel_err"]
        .as_f64()
        .expect("metric present in RESULTS.json");
    assert_eq!(
        found, measured_value,
        "RESULTS.json must carry the exact measured value, no transcription drift"
    );

    // And the same number (formatted) appears in the Markdown report.
    assert!(
        md.contains("0.0000123456") || md.contains(&measured_value.to_string()),
        "RESULTS.md should display the measured value"
    );
}

#[test]
fn test_report_check_detects_hand_edit() {
    let runs_dir = tempfile::tempdir().unwrap();
    let results_dir = tempfile::tempdir().unwrap();

    let input = MetricsInput {
        config_sha256: "check-config".to_string(),
        dataset_sha256: "none".to_string(),
        seed: 0,
        backend: "cpu".to_string(),
        wall_clock_s: 0.0,
        metrics: json!({ "gradcheck_max_rel_err": 1e-6 }),
    };
    write_metrics(runs_dir.path(), "check-run", input).unwrap();

    let cfg = ReportConfig {
        runs_dir: runs_dir.path(),
        gates_toml: &workspace_root().join("gates.toml"),
        results_dir: results_dir.path(),
        workspace_root: &workspace_root(),
    };
    generate(&cfg).unwrap();

    // Hand-edit the committed RESULTS.md -- this must be caught by `--check`.
    let md_path = results_dir.path().join("RESULTS.md");
    let mut md = std::fs::read_to_string(&md_path).unwrap();
    md.push_str("\nhand-edited line that should never survive --check\n");
    std::fs::write(&md_path, md).unwrap();

    let drifted =
        qilm_train::report::check(&cfg).expect("check should run (report itself succeeds)");
    assert!(
        !drifted,
        "check must detect the hand-edited RESULTS.md as drifted"
    );
}

/// Regression test: a committed RESULTS.md/json necessarily records the
/// git_sha of the commit BEFORE it (a file can't know its own future commit
/// hash), so on every later commit a fresh regeneration's git_sha will
/// legitimately differ from the committed one even when NOTHING about the
/// metrics changed. `check()` must not treat that alone as drift, or CI would
/// fail on every single commit forever.
#[test]
fn test_report_check_ignores_git_sha_churn_across_commits() {
    let runs_dir = tempfile::tempdir().unwrap();
    let results_dir = tempfile::tempdir().unwrap();

    let input = MetricsInput {
        config_sha256: "churn-config".to_string(),
        dataset_sha256: "none".to_string(),
        seed: 0,
        backend: "cpu".to_string(),
        wall_clock_s: 0.0,
        metrics: json!({ "gradcheck_max_rel_err": 5e-7 }),
    };
    write_metrics(runs_dir.path(), "churn-run", input).unwrap();

    let cfg = ReportConfig {
        runs_dir: runs_dir.path(),
        gates_toml: &workspace_root().join("gates.toml"),
        results_dir: results_dir.path(),
        workspace_root: &workspace_root(),
    };
    generate(&cfg).unwrap();

    // Simulate "this RESULTS.md was committed against an earlier commit":
    // rewrite every occurrence of the real (current) git_sha with a
    // plausible-but-different "parent commit" sha, in both committed files.
    let real_sha = actual_head_sha();
    let fake_parent_sha = "0".repeat(real_sha.len());

    for name in ["RESULTS.md", "RESULTS.json"] {
        let path = results_dir.path().join(name);
        let contents = std::fs::read_to_string(&path).unwrap();
        let rewritten = contents.replace(&real_sha, &fake_parent_sha);
        assert_ne!(
            contents, rewritten,
            "the real sha should have been present in {name}"
        );
        std::fs::write(&path, rewritten).unwrap();
    }

    // runs_dir still has the ACTUAL current-HEAD run (untouched), so a fresh
    // regeneration is provenance-valid; only the *committed copy's* recorded
    // git_sha is "stale" in the parent-commit sense, and that alone must not
    // register as drift.
    let matches =
        qilm_train::report::check(&cfg).expect("check should succeed (runs/ is still HEAD-valid)");
    assert!(
        matches,
        "git_sha churn alone (metrics unchanged) must not be reported as drift"
    );
}

fn actual_head_sha() -> String {
    let out = std::process::Command::new("git")
        .arg("rev-parse")
        .arg("HEAD")
        .current_dir(workspace_root())
        .output()
        .expect("git must be available");
    String::from_utf8_lossy(&out.stdout).trim().to_string()
}
